### ISSUE TITLE
Future Enhancement: Align Headphone jacks

### ISSUE THREAD

**Issue by eyuan-creare** [Tympan/Tympan_Earpiece_Shield#2]
Headphone jacks are off a minute, inconsequential amount: 0.007"

![image](https://user-images.githubusercontent.com/42774675/77463331-d52d4280-6ddb-11ea-9fcc-39f57bafb12d.png)

**Comment by biomurph** [comment]
Moved the OUTPUT jack 0.2mm to align with the INPUT jack

**Comment by eyuan-creare** [comment]
Thanks... my OCD appreciates it. :)
